services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - server

volumes:
  pgdata:
